### ISSUE TITLE
Github Updater Token Deprecated Since V6.1.0

### ISSUE THREAD

**Issue by SooBahkDo** [afragen/github-updater-additions#1]
Hello All,

Are there plans to update this?

Objectcomponent: "Plugin: github-updater-develop"file: "wp-includes/functions.php"line: 4104message: "github_updater_token_distribution is deprecated since version 6.1.0! Use github_updater_set_options instead."stack: Array(4)0: "_deprecated_hook()"1: "apply_filters_deprecated()"2: "Fragen\GitHub_Updater\Base->set_options_filter()"3: "do_action('init')"length: 4__proto__: Array(0)type: "notice"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
(anonymous) @ query-monitor.js?ver=1527014145:300

Thanks

**Comment by afragen** [comment]
The answer is in the message. Use ‘github_updater_set_options’ filter.
